### ISSUE TITLE
Should XExtensionItemMutableParameters be replaced with a builder class?

### ISSUE THREAD

**Issue by irace** [tumblr/XExtensionItem#1]
Mutability should be avoided. A great way to provide an easy-to-use object creation API is by using the [builder pattern](http://en.wikipedia.org/wiki/Builder_pattern).

Unfortunately, many Objective-C developers seem adverse to using builders. As such, the first version of this library includes the `XExtensionItemMutableParameters` subclass, which allows one to create an `XExtensionItemParameters` instance without using [its initializer (which takes a large number of arguments)](https://github.com/tumblr/XExtensionItem/blob/master/XExtensionItem/XExtensionItemParameters.h#L171).

I'd prefer a builder but want this library to be as approachable as possible. The introduction of a builder class means [`XExtensionItemMutableParameters`](https://github.com/tumblr/XExtensionItem/blob/master/XExtensionItem/XExtensionItemMutableParameters.h) would be deleted altogether, and `XExtensionItemParameters`'s large initializer would be made private. The only way to get an instance would be to use the builder object and then call `build` at the end.

**Comment by irace** [comment]
I think keeping the mutable subclass around but providing a convenience initializer that takes a block with an `XExtensionItemMutableParameters` instance as the argument is a good balance. It keeps the mutable class around for those who are allergic to builders, yet adds a convenient way to initialize that doesn’t require calling the (currently very long) designated initializer. 

```objc
- (instancetype)initWithBlock:(void (XExtensionItemMutableParameters *mutableParameters));
```

**Comment by mattbischoff** [comment]
Agreed. Great solution.
