### ISSUE TITLE
Project structure should match what `pod lib create` generates

### ISSUE THREAD

**Issue by mattbischoff** [tumblr/XExtensionItem#10]
Is two Xcode projects confusing? @twigz seems to think so. The arguments I can remember him making:

1. It’s not the default from `pod lib create`
2. If you’re working on the library in the normal code → test your code in the sample app workflow, it’s more difficult to run the unit tests.

**Comment by irace** [comment]
I think I’m going to revert this. The single Xcode project structure doesn’t enable me to easily add Carthage support as well :confused:
