### ISSUE TITLE
Look into replacing `UTIsToContentTypeRepresentations` with sugar on top of `NSItemProvider` item registration

### ISSUE THREAD

**Issue by irace** [tumblr/XExtensionItem#14]

**Comment by irace** [comment]
LOL nope, registering multiple items with a single `NSItemProvider` still has the same pitfalls of multiple items, or one item with multiple attachments: https://github.com/tumblr/ios-extension-issues/issues/5

**Comment by AriX** [comment]
That sucks. But frankly even if this weren't the case, this would still be a bad idea, because types registered with an NSItemProvider are not registered in a deterministic order.

**Comment by irace** [comment]
> That sucks. But frankly even if this weren't the case, this would still be a bad idea, because types registered with an NSItemProvider are not registered in a deterministic order.

True, but I’m currently just using a dictionary to store additional content representations, so they don’t have any intrinsic order either.

¯\\_(ツ)_/¯

**Comment by AriX** [comment]
Yeah for sure, though the important part is that the main/preferred representation be distinguishable from alternate ones, which is achieved by storing both a dictionary and the item provider. Not ideal though.

**Comment by irace** [comment]
:+1:
