### ISSUE TITLE
Add additional parameters to `XExtensionItemSourceApplication`

### ISSUE THREAD

**Issue by irace** [tumblr/XExtensionItem#17]
Talk with @chrismaddern to make sure we’re on the same page with regards to which parameters apps should use to attribute themselves.

Here’s what we have so far: https://github.com/tumblr/XExtensionItem/blob/master/XExtensionItem/XExtensionItemSourceApplication.h

**Comment by irace** [comment]
It looks as though the [Button Deep Link Interoperability RFC only](https://www.usebutton.com/api/dpl-io/) includes the following:

* Store ID
* App name
* Display title

The first two are already included in [XExtensionItemSourceApplication](https://github.com/tumblr/XExtensionItem/blob/master/XExtensionItem/XExtensionItemSourceApplication.h) and display title doesn’t really make sense in the context of share extensions, so maybe we don’t have too much to discuss after all?

**Comment by irace** [comment]
After some internal discussion it seems like it’s worth adding the following optional properties as well:

* Google Play ID
* Web URL
* iOS app URL
* Android app URL

One could envision a scenario in which an app, e.g. Instapaper, shares into a service like Tumblr and we want to be able to give users who view the post the option to either install the app if they don't already have it, or deep-link in if they do.

**Comment by mattbischoff** [comment]
Can’t the iOS App URL be derived from the app ID?

**Comment by irace** [comment]
> Can’t the iOS App URL be derived from the app ID?

This would be an _app_ URL like `instapaper://x-callback-url?article=12345`

**Comment by mattbischoff** [comment]
Ah, okay. Got it.

**Comment by AriX** [comment]
👍
