### ISSUE TITLE
Add the ability to provide alternative items on a per-activity type basis

### ISSUE THREAD

**Issue by irace** [tumblr/XExtensionItem#33]
Provide hooks for giving specific items to specific activities, instead of simply passing the same fully-populated `NSExtensionItem` everywhere (e.g. to send different representations to Twitter, Facebook, Mail.app, etc.)

I can think of three different ways to register alternative items off the top of my head (these methods would all be on [XExtensionItemSource](https://github.com/tumblr/XExtensionItem/blob/feature/activity-item-source/Pod/Classes/XExtensionItem.h#L47):

```objc
@implementation XExtensionItemSource

...

// Simplest – just provide a value that should be used in place of the default `NSExtensionItem` if a specific activity is picked
- (void)registerItem:(id)item forActivityType:(NSString *)activityType;

// More complex – provide a block that returns a value, to avoid necessarily creating values for activities that may never be selected
- (void)registerItemProvider:(void (^)())itemProvider forActivityType:(NSString *)activityType;

// Most flexible – provide an object that determines what item should be returned for an activity type

@property (nonatomic) id <XExtensionItemProvider> alternativeItemProvider;

@end

@protocol XExtensionItemProvider

- (id)itemForActivityType:(NSString *)activityType;

@end
```

Usage would look something like:

```objc
[itemSource registerItem:twitterLengthSummaryString forActivityType: UIActivityTypePostToTwitter];

[itemSource registerItemProvider:^{
    // Lazily compute the Twitter-specific summary
    return twitterLengthSummaryString;
} forActivityType: UIActivityTypePostToTwitter];

@implementation MyAppCustomActivityItemProvider <XExtensionItemProvider>

- (id)itemForActivityType:(NSString *)activityType {
    if (activityType == UIActivityTypePostToTwitter) {
        return self.twitterLengthSummaryString;
    }

    // Returning `nil` would mean the activity/extension gets the default `NSItemProvider` instead of something special
    return nil;
}

@end

itemSource.alternativeItemProvider = [[MyAppCustomActivityItemProvider alloc] init];
```

I feel like @arix will have opinions on this one.

**Comment by AriX** [comment]
Seems like a good solution to me!

**Comment by irace** [comment]
> Seems like a good solution to me!

Which of the three above do you like best?

**Comment by AriX** [comment]
The block one definitely feels like the right balance to me.

**Comment by irace** [comment]
> The block one definitely feels like the right balance to me.

One reason it might make more sense to favor the protocol approach is because [I also want to add ways to hook into the `UIActivityItemSource` protocol’s optional methods](https://github.com/tumblr/XExtensionItem/issues/35) which can be used to provide subjects and thumbnail images (data type identifiers as well, though I’m not sure how useful that is for us).

I suppose we could add three methods to `XExtensionItemSource` like:

```objc
@interface XExtensionItemSource

- (void)registerThumbnailImage:(UIImage *)image forActivityType:(NSString *)activityType;

- (void)registerSubject:(NSString *)subject forActivityType:(NSString *)activityType;

- (void)registerItemProvider:(void (^)())itemProvider forActivityType:(NSString *)activityType;

@end
```

But this may be cleaner as a separate object? Particularly since registering a thumbnail image isn’t particularly useful until the system tells you what size it wants it to be:

```objc
@protocol XExtensionItemProvider

- (id)itemForActivityType:(NSString *)activityType;
 
- (NSString *)subjectForActivityType:(NSString *)activityType;

- (UIImage *)thumbnailImageForActivityType:(NSString *)activityType suggestedSize:(CGSize)size;
```

Alternatively, just the thumbnail image could be provided via a protocol, and the other two `register` methods could be aded directly to `XExtensionItemSource`.

**Comment by AriX** [comment]
Couldn't the thumbnail image just be delivered via a block? Like you register a block and it gets called (with the suggested size as an argument) when the system actually asks for the image. Seems like a simpler solution to me than doing something protocol-based.

**Comment by AriX** [comment]
`- (void)registerThumbnailProvider:(UIImage *(^)(CGSize suggestedSize))thumbnailBlock forActivityType:(NSString *)activityType;`

**Comment by irace** [comment]
Yep, indeed.
