### ISSUE TITLE
Allow `attributedContentText` to be configured on a per-activity type basis

### ISSUE THREAD

**Issue by irace** [tumblr/XExtensionItem#40]
As requested by @prendio2:

Certain built-in system activities (Facebook/Twitter/Vimeo/Flickr and [possibly Weibo](https://github.com/tumblr/XExtensionItem/issues/39)) [can consume an `NSExtensionItem` as input](https://github.com/tumblr/XExtensionItem/pull/38), and display the `attributedContentText` value. `XExtensionItem` does not currently provide a way to customize this `attributedContentText` value on a per-activity item basis, however.

One _could_ use the new `registerItemProvidingBlock:forActivityType:` method added in [this pull request](https://github.com/tumblr/XExtensionItem/pull/37), but if they wanted to pass an image/string/etc. to the Twitter activity as well, the caller would need to build an `NSExtensionItem` themselves in order to provide a Twitter-specific `attributedContentText` value. This is suboptimal as part of `XExtensionItem`’s mission is to prevent users from having to construct `NSExtensionItem` instances themselves.

This isn’t as useful for Flickr, Vimeo, or Facebook, since it’s safe to assume that anyone who shares using those extensions also has the apps installed – if so, the app’s extension takes precedence and [promptly throws the `attributedContentText` on the floor](https://github.com/tumblr/XExtensionItem/blob/feature/dont-pass-extension-items-to-certain-system-activities/Pod/Classes/XExtensionItem.m#L139) ¯\\_(ツ)_/¯

Probably safe to assume that Twitter will add an official share extension of their own at some point, but this would still be useful in the interim.

**Comment by AriX** [comment]
Now covered under #43.
