### ISSUE TITLE
Allow a default `subject` to be provided

### ISSUE THREAD

**Issue by irace** [tumblr/XExtensionItem#41]
As per @prendio – allow a default subject to be provided rather than explicitly registering subjects for individual activity types using the `registerSubject:forActivityType:` method added in [this pull request](https://github.com/tumblr/XExtensionItem/pull/37).

(This isn’t particularly pressing since there isn’t public API for extensions to read this value, and only Mail and Messages support subjects out of the built-in activities (which only change once a year, at most), but we only just realized that the latter does yesterday, so who knows what else we could potentially be missing?)

A couple of options:

* Use the `attributedTitle` value if it exists and a subject was not explicitly registered for a given activity type
* Add a `@property (nonatomic, copy) NSString *defaultSubject;` property
* Document that calling `registerSubject:forActivityType:` with a `nil` activity type will register it as the default. I think I like this one the best.

Thoughts?

**Comment by prendio2** [comment]
`registerSubject:forActivityType:` with `nil` activity seems like a good call to me

**Comment by AriX** [comment]
Using `attributedTitle` as a fallback default also seems like a good idea.

**Comment by irace** [comment]
I think either would be good but [this issue spelling out how complicated the API is becoming](https://github.com/tumblr/XExtensionItem/issues/43) might be a compelling reason for favoring `attributedTitle`.

**Comment by irace** [comment]
Closing in favor of the refactor proposed in this issue: https://github.com/tumblr/XExtensionItem/issues/43
