### ISSUE TITLE
Should provider types return `id` types?

### ISSUE THREAD

**Issue by irace** [tumblr/XExtensionItem#49]
Consider the following use case: in general, you are sharing a URL but want to provide a custom HTML email if the Mail activity is chosen. You’d write code like the following:

```objc
[[XExtensionItemSource alloc] initWithURLProvider:^(NSString *activityType) {
    if (activityType == UIActivityTypeMail) {
        return HTMLEmailString;
    }
    else {
        return URL;
    }
}];
```

This wouldn’t compile though, since the URL provider block is typed to return an `NSURL`. Should it be typed to return an `id` instead? This way the developer can return non-URL types for activities that they know can take those non-URL types as inputs.

@AriX

**Comment by AriX** [comment]
Yeah I suppose that makes sense. We would additionally have to make sure that self.typeIdentifier is not consulted when putting together the main attachment's NSItemProvider, and instead use the static function that returns the type identifier given an activity item.
